name: Release database change

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Add IP Address
        env:
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}   
        run: |
          IP_ADDRESS=`curl ifconfig.io`
          aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 3306 --cidr "$IP_ADDRESS"/32
      - name: Run migration
        run: migrate -path db/migration -verbose -database 'mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@tcp(${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }})/tokyo_takeout' up
      - name: Remove IP Address
        env:
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}   
        if: ${{ always() }}
        run: |
          IP_ADDRESS=`curl ifconfig.io`
          aws ec2 revoke-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 3306 --cidr "$IP_ADDRESS"/32        
